### PR TITLE
Add ProviderAlias attribute to JournalLoggerProvider (#33)

### PR DESCRIPTION
**Pull request by ATLSAPI**
Pull request created. Let me know if need me to increment the patch version.

### CODE REVIEW

**Comment by tmds** [comment]
Can you add something to the README too?

Suggestion:

The logger can be configured in `appsettings.json` using the `Journal` alias. For example:
```
"Logging": {
...
	"Journal": {
		"IncludeScopes": false,
		"LogLevel": {
			"Default": "Warning",
			"Microsoft.AspNetCore.Hosting.Internal.WebHost": "Information"
		}
	}
...
}
```

Please put it just above _The logging added is structured logging_.

**Comment by ATLSAPI** [comment]
That's useful. Will add in 👍

**Comment by tmds** [comment]
Thank you!

**Comment by tmds** [comment]
I published 0.6.0 to nuget.org.

**Pull request merged**
